

site_name: SNSPD Wiki
dev_addr: 127.0.0.1:9254
# site_dir: docs.snspd.xyz
  
theme:
  name: material
  # logo: images/logo.svg
  # favicon: images/favicon.png
  palette: 
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # custom_dir: overrides
  features:
    - navigation.indexes

extra_css:
  - stylesheets/extra.css
        
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      check_paths: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  # - pymdownx.superfences
  # - footnotes

# extra:
#   analytics:
#     provider: google
#     property: G-95QS2HZSZW
#     # 3565859434

    


# nav:
#   - index.md
#   - High Rate Entanglement:
#     - hre/index.md
#     - April 2022: hre/hre_april_2022.md
#     - May 2022: hre/hre_may_2022.md
#     - Ultra Long Distance Demos: hre/hre_ultra.md
#     - Fast Entanglement Scans: hre/fast_ent_scans.md
#     - Action Framework: hre/action_framework.md
#   - DDAQ Software: ddaq.md



  

extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  
 # TO DEPLOY

 # mkdocs build
 # sudo cp -R docs.snspd.xyz/ /var/www/

